"""Added relation between users and workspaces tables

Revision ID: 17c4f3f56d9b
Revises: 2cd3dfe997ef
Create Date: 2024-07-09 15:44:55.402444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = "17c4f3f56d9b"
down_revision: Union[str, None] = "2cd3dfe997ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("assigned_workspace_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "workspace_chief",
            sa.Boolean(),
            nullable=False,
            server_default=sa.func.cast(false(), sa.Boolean()),
        ),
    )
    op.create_foreign_key(
        op.f("fk_users_assigned_workspace_id_workspaces"),
        "users",
        "workspaces",
        ["assigned_workspace_id"],
        ["id"],
    )
    op.drop_constraint("fk_workspaces_chief_id_users", "workspaces", type_="foreignkey")
    op.drop_column("workspaces", "chief_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces",
        sa.Column("chief_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_workspaces_chief_id_users",
        "workspaces",
        "users",
        ["chief_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_users_assigned_workspace_id_workspaces"),
        "users",
        type_="foreignkey",
    )
    op.execute("ALTER TABLE users ALTER COlUMN workspace_chief DROP DEFAULT;")
    op.drop_column("users", "workspace_chief")
    op.drop_column("users", "assigned_workspace_id")
    # ### end Alembic commands ###
