services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - equeue-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - equeue-network
    command: >
        sh -c "
          alembic upgrade head && gunicorn main:app 
            --workers 3 
            --worker-class uvicorn.workers.UvicornWorker 
            --bind=0.0.0.0:8000 
            --access-logfile -
        "

networks:
  equeue-network:

volumes:
  postgres_data:
