name: Render.com auto-deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH__TOKEN }}
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          api-key: ${{ secrets.RENDER_COM__API_KEY }}
          service-id: ${{ secrets.RENDER_COM__SERVICE_ID }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
